version: "2"
services:
  node:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: "kson"
    command: npm start
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=dev
    volumes:
      - ./server/:/usr/src/app/server
    ports:
      - 8080:8080
      - 9229:9229